# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f16174dca45cc536f061dda4b83f0e0afcd0326dda97d2d8cf22c6130e8477c4872d3a4f326adc0b5395a42c935d7ac69918679dcdd00bb37f5cdc87f5d6feb2

test:
  secret_key_base: c8b52d8f8a5dbb50fb4cd4a9c9b26e58bf1479a152757764878215a800d246758b7421dbcef8e5e3daa638445634919914e2165ae73f6789fe6f0fa55244b3b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
